### ISSUE TITLE
Write music-extract script

### ISSUE THREAD

**Issue by rootCircle** [iiitl/bash-practice-repo-24#91]
Make a ffmpeg script which takes all the mp4 files in a folder (recursively) and output them in the same position mp3 file

E.g.:
```
Videos
├── Clips
│   ├── clip1.mp4
│   └── clip2.mp4
├── Movies
│   ├── movie1.mp4
│   └── movie2.mp4
└── Songs
    ├── Song1.mp4
    └── Song2.mp4
```

On command `$ music-extract Videos`: The above folder will create another folder with the position of file with just there audio

```
Music
├── Clips
│   ├── clip1.mp3
│   └── clip2.mp3
├── Movies
│   ├── movie1.mp3
│   └── movie2.mp3
└── Songs
    ├── Song1.mp3
    └── Song2.mp3
```

After writing script send a PR mentioning this issue by putting "#\<number of this issue\>" in your PR (optionally also in the commit).

**Comment by shuklamaneesh23** [comment]
@rootCircle ,can you please assign this issue to me.
I would write such a script that traverses directories recursively, identifies MP4 files, then utilizes ffmpeg to extract their audio, saving the output as MP3 files in a designated directory. It provides progress updates during the extraction process, facilitating efficient conversion of video files to audio.

**Comment by Sidharth-Singh10** [comment]
@rootCircle , Can you assign me this issue. I would like to work on it

**Comment by rootCircle** [comment]
sure @shuklamaneesh23 @Sidharth-Singh10, go ahead with your implementation, ping me here if you need any help!

**Comment by Priyanshu-2005** [comment]
@rootCircle , I would like to work on this issue kindly assign me the issue

**Comment by rootCircle** [comment]
Sure @, go ahead with your implementation!

**Comment by rootCircle** [comment]
@shuklamaneesh23 your last PR(#113) was marked invalid! Ping me if you still need to work on this! Unassigned for now!

**Comment by shuklamaneesh23** [comment]
@rootCircle ,sir please allow me to work upon it again as I want to fix the issue.

**Comment by rootCircle** [comment]
@shuklamaneesh23 sure go ahead!

**Comment by ArshiaAdhya** [comment]
Hi @rootCircle 
I can work on this issue. Please assign this to me.

**Comment by rootCircle** [comment]
Hi @ArshiaAdhya , this issue already has max limit of assignes of 3, please try on some other issues in meantime

**Comment by rootCircle** [comment]
Hi @ArshiaAdhya , you can actually work on this as @Sidharth-Singh10 implementation was not accepted! Go ahead, all the best!
